<!DOCTYPE html>
<html>

<head>
	<title>Refer&#234;ncia de objeto n&#227;o definida para uma inst&#226;ncia de um objeto.</title>
	<meta name="viewport" content="width=device-width" />
	<style>
		body {
			font-family: "Verdana";
			font-weight: normal;
			font-size: .7em;
			color: black;
		}

		p {
			font-family: "Verdana";
			font-weight: normal;
			color: black;
			margin-top: -5px
		}

		b {
			font-family: "Verdana";
			font-weight: bold;
			color: black;
			margin-top: -5px
		}

		H1 {
			font-family: "Verdana";
			font-weight: normal;
			font-size: 18pt;
			color: red
		}

		H2 {
			font-family: "Verdana";
			font-weight: normal;
			font-size: 14pt;
			color: maroon
		}

		pre {
			font-family: "Consolas", "Lucida Console", Monospace;
			font-size: 11pt;
			margin: 0;
			padding: 0.5em;
			line-height: 14pt
		}

		.marker {
			font-weight: bold;
			color: black;
			text-decoration: none;
		}

		.version {
			color: gray;
		}

		.error {
			margin-bottom: 10px;
		}

		.expandable {
			text-decoration: underline;
			font-weight: bold;
			color: navy;
			cursor: hand;
		}

		@media screen and (max-width: 639px) {
			pre {
				width: 440px;
				overflow: auto;
				white-space: pre-wrap;
				word-wrap: break-word;
			}
		}

		@media screen and (max-width: 479px) {
			pre {
				width: 280px;
			}
		}
	</style>
</head>

<body bgcolor="white">

	<span><H1>Erro de Servidor no Aplicativo '/'.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Refer&#234;ncia de objeto n&#227;o definida para uma inst&#226;ncia de um objeto.</i> </h2></span>

	<font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

		<b> Descrição: </b>Ocorreu uma exceção sem tratamento durante a execução da atual solicitação da Web. Examine o
		rastreamento de pilha para obter mais informações sobre o erro e onde foi originado no código.

		<br><br>

		<b> Detalhes da Exceção: </b>System.NullReferenceException: Refer&#234;ncia de objeto n&#227;o definida para uma
		inst&#226;ncia de um objeto.<br><br>

		<b>Erro de Origem:</b> <br><br>

		<table width=100% bgcolor="#ffffcc">
			<tr>
				<td>
					<code><pre>

Linha 39:                 //check if the response body contains access token if so then do your processing
Linha 40: 
<font color=red>Linha 41:                 sessao.AutorizacaoHash = (string)responseBody.access_token;
</font>Linha 42:                 serviceSessao.Salvar(sessao);
Linha 43:             }</pre></code>

				</td>
			</tr>
		</table>

		<br>

		<b> Arquivo de Origem: </b>
		C:\Users\MaiconBischoffBischo\Documents\Projetos\omega-api\OmegaAPI\Omega.API\Providers\ResponseMiddleware.cs<b> &nbsp;&nbsp; Linha: </b>
		41
		<br><br>

		<b>Rastreamento de Pilha:</b> <br><br>

		<table width=100% bgcolor="#ffffcc">
			<tr>
				<td>
					<code><pre>

[NullReferenceException: Refer&#234;ncia de objeto n&#227;o definida para uma inst&#226;ncia de um objeto.]
   Omega.Lib.Models.Providers.&lt;Invoke&gt;d__1.MoveNext() in C:\Users\MaiconBischoffBischo\Documents\Projetos\omega-api\OmegaAPI\Omega.API\Providers\ResponseMiddleware.cs:41
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   Omega.API.&lt;&lt;ConfigureAuth&gt;b__8_0&gt;d.MoveNext() in C:\Users\MaiconBischoffBischo\Documents\Projetos\omega-api\OmegaAPI\Omega.API\App_Start\Startup.Auth.cs:41
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.&lt;RunApp&gt;d__5.MoveNext() +197
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.&lt;DoFinalWork&gt;d__2.MoveNext() +184
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +117
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +510
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +131
</pre></code>

				</td>
			</tr>
		</table>

		<br>

		<hr width=100% size=1 color=silver>

		<b>Informações sobre a Versão:</b>&nbsp;Microsoft .NET Framework Versão:4.0.30319; Versão do ASP.NET:4.7.3429.0

	</font>

</body>

</html>
<!-- 
[NullReferenceException]: Refer&#234;ncia de objeto n&#227;o definida para uma inst&#226;ncia de um objeto.
   em Omega.Lib.Models.Providers.AuthenticationMiddleware.<Invoke>d__1.MoveNext() na C:\Users\MaiconBischoffBischo\Documents\Projetos\omega-api\OmegaAPI\Omega.API\Providers\ResponseMiddleware.cs:linha 41
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em Omega.API.Startup.<>c.<<ConfigureAuth>b__8_0>d.MoveNext() na C:\Users\MaiconBischoffBischo\Documents\Projetos\omega-api\OmegaAPI\Omega.API\App_Start\Startup.Auth.cs:linha 41
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   em System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   em System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   em System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-->